
services:
    userservice:
        build: 
            context: .
            dockerfile: UserService/Dockerfile
        ports:
            - "5003:5001"
        environment:
            - ASPNETCORE_URLS=http://+:5001
            - ProductService__BaseUrl=http://productservice:80
            - ConnectionStrings__UsersDb=Server=usersdb;Database=UsersDb;User Id=sa;Password=Your_password123;
            - Jwt__ExpireHours=${Jwt__ExpireHours}
            - Jwt__ExpireMinutesForEmailConfirmation=${Jwt__ExpireMinutesForEmailConfirmation}
            - Jwt__ExpireMinutesForPasswordConfirmation=${Jwt__ExpireMinutesForPasswordConfirmation}
            - Jwt__SecretKey=${Jwt__SecretKey}
            - Jwt__SecretKeyForEmailConfirmation=${Jwt__SecretKeyForEmailConfirmation}
            - Jwt__SecretKeyForPasswordConfirmation=${Jwt__SecretKeyForPasswordConfirmation}
            - Smtp__AppPassword=${Smtp__AppPassword}
            - Smtp__Email=${Smtp__Email}
            - Smtp__Host=${Smtp__Host}
            - Smtp__Port=${Smtp__Port}
        depends_on:
            - usersdb

    productservice:
        build:
            context: .
            dockerfile: ProductService/Dockerfile
        ports:
            - "5002:5000"
        environment:
            - ASPNETCORE_URLS=http://+:5000
            - ConnectionStrings__ProductsDb=Server=productsdb;Database=ProductsDb;User Id=sa;Password=Your_password123;
            - Jwt__ExpireHours=${Jwt__ExpireHours}
            - Jwt__ExpireMinutesForEmailConfirmation=${Jwt__ExpireMinutesForEmailConfirmation}
            - Jwt__ExpireMinutesForPasswordConfirmation=${Jwt__ExpireMinutesForPasswordConfirmation}
            - Jwt__SecretKey=${Jwt__SecretKey}
            - Jwt__SecretKeyForEmailConfirmation=${Jwt__SecretKeyForEmailConfirmation}
            - Jwt__SecretKeyForPasswordConfirmation=${Jwt__SecretKeyForPasswordConfirmation}
        depends_on:
            - productsdb

    usersdb:
        image: mcr.microsoft.com/mssql/server:2022-latest
        container_name: usersdb
        environment:
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"
        ports:
            - "1434:1433"
        volumes:
            - users_data:/var/opt/mssql

    productsdb:
        image: mcr.microsoft.com/mssql/server:2022-latest
        container_name: productsdb
        environment:
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"
        ports:
            - "1435:1433"
        volumes:
            - products_data:/var/opt/mssql

volumes:
  users_data:
  products_data: